[env:yolo_uno]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM14
monitor_port = COM14

board_build.filesystem = littlefs
build_src_filter =
	+<*>
	-<tinyml.cpp>
	-<camera_mnist_task.cpp>

build_flags = 
	-DSSID_AP='"ESP32 LOCAL"'
	-DPASS_AP='12345678'
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1

lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.1
	DHT20
	LCD
	PubSubClient
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	madhephaestus/ESP32Servo@^3.1.3

lib_compat_mode = strict
lib_archive = false
